# Generated by Django 2.2 on 2020-12-17 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=20)),
                ('date_of_birth', models.DateTimeField(default=datetime.datetime(2020, 12, 17, 16, 5, 19, 577269))),
                ('phone_number', models.CharField(max_length=13)),
            ],
        ),
    ]
